spring:
  application:
    name: reservation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: reservation
    password: reservation

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: reservation
    password: reservation

server:
  port: 8080
